### ISSUE TITLE
How to Slave read rom command 

### ISSUE THREAD

**Issue by praveen-petal** [bfabiszewski/owslave#1]
Hai,
I want slave read rom command from master in 8051 IC. How to read it.

Thanks & Regards
M.Praveen

**Comment by bfabiszewski** [comment]
This project is only for PIC16. You will have to port it to another device

**Comment by praveen-petal** [comment]
any posibility for using your in 8051

**Comment by bfabiszewski** [comment]
You would have to rewrite the code to adjust it to another controller
